---
- name: Debian specific tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: EL7 specific tasks
  ansible.builtin.include_tasks: rhel7.yml
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version | int == 7

- name: EL>7 specific tasks
  ansible.builtin.include_tasks: rhel8.yml
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version | int > 7

- name: Apply log4shell mitigation
  ansible.builtin.copy:
    content: "-Dlog4j2.formatMsgNoLookups=true"
    dest: /etc/elasticsearch/jvm.options.d/log4shell.options
    owner: root
    group: root
    mode: "0644"
  notify: Restart elasticsearch

- name: Adjust Elasticsearch heap size
  ansible.builtin.replace:
    path: /etc/elasticsearch/jvm.options
    regexp: '^-{{ item }}.*'
    replace: '-{{ item }}{{ opencast_elasticsearch_heap_size }}'
  notify: Restart elasticsearch
  loop:
    - Xms
    - Xmx

- name: Start and enable elasticsearch service
  ansible.builtin.systemd:
    name: elasticsearch
    enabled: true
