---

name: ansible lint

on:  # yamllint disable-line rule:truthy
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: pip3 install ansible ansible-lint yamllint molecule

      - name: install roles from galaxy
        run: ansible-galaxy install elan.opencast_repository

      - name: create lxc container
        uses: lkiesow/setup-lxc-container@v1
        with:
          dist: centos
          release: 9-Stream

      - name: ansible lint
        run: ansible-lint

      - name: yamllint
        run: yamllint -c .yamllint .

      - name: run molecule tests
        run: molecule test
